In [3]:
lambda_=lambda argument1, argument2: argument1+argument2;
print ("the value of the function",lambda_(30,40))


the value of the function 70


In [20]:
import numpy as np
from time import process_time
python_list=[i for i in range(10000)]
start_time=process_time()
end_time=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)


0.0


In [27]:
import numpy as np
from time import process_time
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0


In [29]:
print(type(np_array))

<class 'numpy.ndarray'>


In [30]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [32]:
a.shape

(4,)

In [33]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [34]:
b=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(b)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [35]:
b.shape

(2, 4)

In [37]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [38]:
x=np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [39]:
x=np.full((4,5),3)
print(x)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [42]:
x=np.eye((4))
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [43]:
x=np.random.random((4,5))
print(x)

[[0.62130491 0.72295613 0.88624696 0.21695293 0.37534891]
 [0.56834123 0.78964123 0.5139339  0.48326121 0.72842791]
 [0.26226861 0.90212066 0.6119795  0.46422193 0.05499492]
 [0.55299218 0.29230967 0.02149984 0.5894936  0.17245033]]
